[app]
  environment = "development"
  listen_address = "0.0.0.0:9527"
  otp_required = true
  auth_providers = ["telegram"]

[channels]
  [channels.telegram]
    bot_token = "Your Telegram Bot Token"
    recipients = [1231321]

  [channels.http]
    endpoint = "https://httpbin.org/post"
    headers = { "Content-Type" = "application/json", "Authorization" = "Bearer 1234567890" }
